-- Matrix Theme
-- Green-on-black hacker aesthetic

void_themes.register("Matrix", {
    name = "Matrix",
    desc = "Green-on-black hacker aesthetic",
    ui = {
        status_bar_bg = "black",
        status_bar_fg = "green",
        status_bar_active_bg = "dark_green",
        status_bar_active_fg = "light_green",
        status_bar_activity_bg = "black",
        status_bar_activity_fg = "green",
        status_bar_info_fg = "green",
        topic_bar_bg = "black",
        topic_bar_fg = "light_green",
        input_fg = "light_green",
        border = "green",
        timestamp = "dark_gray",
    },
    messages = {
        normal = "green",
        action = "light_green",
        system = "cyan",
        notice = "light_green",
        highlight = "white",
        error = "red",
        server = "dark_gray",
        ctcp = "red",
    },
    nicks = {
        op = "light_green",
        op_nick = "light_green",
        voice = "green",
        voice_nick = "green",
        halfop = "cyan",
        halfop_nick = "green",
        founder = "light_green",
        founder_nick = "light_green",
        admin = "light_green",
        admin_nick = "light_green",
        normal = "green",
        normal_prefix = "dark_gray",
    },
})
