-- Nord Theme (inspired by MiMo-Code nord.json)
-- Arctic, north-bluish color palette

void_themes.register("Nord", {
    name = "Nord",
    desc = "Arctic north-bluish color palette",
    ui = {
        status_bar_bg = "dark_blue",
        status_bar_fg = "white",
        status_bar_active_bg = "light_blue",
        status_bar_active_fg = "black",
        status_bar_activity_bg = "dark_gray",
        status_bar_activity_fg = "white",
        status_bar_info_fg = "white",
        topic_bar_bg = "dark_blue",
        topic_bar_fg = "white",
        input_fg = "cyan",
        border = "dark_gray",
        timestamp = "dark_gray",
    },
    messages = {
        normal = "green",
        action = "yellow",
        system = "cyan",
        notice = "magenta",
        highlight = "white",
        error = "light_red",
        server = "dark_gray",
        ctcp = "red",
    },
    nicks = {
        op = "red",
        op_nick = "light_green",
        voice = "yellow",
        voice_nick = "green",
        halfop = "cyan",
        halfop_nick = "green",
        founder = "magenta",
        founder_nick = "light_green",
        admin = "red",
        admin_nick = "light_green",
        normal = "green",
        normal_prefix = "dark_gray",
    },
})
