-- Tokyo Night Theme — dark theme with vibrant accents
void_themes.register("TokyoNight", {
    name = "TokyoNight",
    desc = "Dark theme inspired by Tokyo's night lights",
    ui = {
        status_bar_bg = "dark_blue",
        status_bar_fg = "white",
        status_bar_active_bg = "light_blue",
        status_bar_active_fg = "black",
        status_bar_activity_bg = "dark_gray",
        status_bar_activity_fg = "white",
        status_bar_info_fg = "white",
        topic_bar_bg = "dark_magenta",
        topic_bar_fg = "white",
        input_fg = "light_blue",
        border = "dark_gray",
        timestamp = "dark_gray",
    },
    messages = {
        normal = "light_green",
        action = "yellow",
        system = "cyan",
        notice = "light_magenta",
        highlight = "white",
        error = "light_red",
        server = "dark_gray",
        ctcp = "red",
    },
    nicks = {
        op = "light_red",
        op_nick = "light_green",
        voice = "yellow",
        voice_nick = "light_green",
        halfop = "cyan",
        halfop_nick = "light_green",
        founder = "light_magenta",
        founder_nick = "light_green",
        admin = "red",
        admin_nick = "light_green",
        normal = "light_green",
        normal_prefix = "dark_gray",
    },
})
