-- Dracula Theme — vibrant dark theme with neon accents
void_themes.register("Dracula", {
    name = "Dracula",
    desc = "Vibrant dark theme with neon accents (draculatheme.com palette)",
    is_dark = true,
    ui = {
        status_bar_bg = "#44475a",
        status_bar_fg = "#f8f8f2",
        status_bar_active_bg = "#bd93f9",
        status_bar_active_fg = "#282a36",
        status_bar_activity_bg = "#6272a4",
        status_bar_activity_fg = "#f8f8f2",
        status_bar_info_fg = "#8be9fd",
        topic_bar_bg = "#282a36",
        topic_bar_fg = "#f8f8f2",
        input_fg = "#f8f8f2",
        input_prompt_fg = "#bd93f9",
        border = "#6272a4",
        timestamp = "#6272a4",
    },
    messages = {
        normal = "#f8f8f2",
        action = "#f1fa8c",
        system = "#8be9fd",
        notice = "#ff79c6",
        highlight = "#ffb86c",
        error = "#ff5555",
        server = "#6272a4",
        ctcp = "#ff79c6",
        url = "#8be9fd",
    },
    nicks = {
        op = "#ff5555",
        op_nick = "#ff5555",
        voice = "#f1fa8c",
        voice_nick = "#f1fa8c",
        halfop = "#8be9fd",
        halfop_nick = "#8be9fd",
        founder = "#bd93f9",
        founder_nick = "#bd93f9",
        admin = "#ff79c6",
        admin_nick = "#ff79c6",
        normal = "#f8f8f2",
        normal_prefix = "#6272a4",
        header = "#6272a4",
    },
    nick_colors = {
        "#ff5555", "#50fa7b", "#f1fa8c", "#8be9fd",
        "#bd93f9", "#ff79c6", "#ffb86c", "#f8f8f2",
    },
    formats = {
        status_format = "%T %N%# %@%C%+ %W %A %H%B %F %Q%M",
        input_prompt = "> ",
        join = "* $0 has joined $1",
        part = "* $0 has left $1 ($2)",
        quit = "* $0 has quit IRC ($1)",
        kick = "* $0 was kicked from $1 by $2 ($3)",
        nick = "* $0 is now known as $1",
        mode = "* $0 sets mode: $1",
        topic = "* $0 set topic to: $1",
        msg = "<$0> $1",
        notice = "-$0- $1",
        action = "* $0 $1",
        public = "<$0> $1",
    },
    ctcp = {
        version = "Void IRC Client v0.3.0 (Rust)",
        userinfo = "Void IRC Client",
        source = "https://github.com/pshq-ripe/void",
    },
    reasons = {
        kick = "Requested",
        part = "Leaving",
        quit = "Leaving",
    },
})
