-- Dracula Theme — vibrant dark theme with neon accents
void_themes.register("Dracula", {
    name = "Dracula",
    desc = "Vibrant dark theme with neon accents",
    is_dark = true,
    ui = {
        status_bar_bg = "magenta",
        status_bar_fg = "black",
        status_bar_active_bg = "light_magenta",
        status_bar_active_fg = "black",
        status_bar_activity_bg = "dark_gray",
        status_bar_activity_fg = "white",
        status_bar_info_fg = "black",
        topic_bar_bg = "dark_magenta",
        topic_bar_fg = "white",
        input_fg = "light_green",
        input_prompt_fg = "light_magenta",
        border = "dark_gray",
        timestamp = "dark_gray",
    },
    messages = {
        normal = "light_green",
        action = "yellow",
        system = "cyan",
        notice = "light_magenta",
        highlight = "white",
        error = "light_red",
        server = "dark_gray",
        ctcp = "red",
        url = "light_blue",
    },
    nicks = {
        op = "light_red",
        op_nick = "light_green",
        voice = "yellow",
        voice_nick = "light_green",
        halfop = "cyan",
        halfop_nick = "light_green",
        founder = "light_magenta",
        founder_nick = "light_green",
        admin = "red",
        admin_nick = "light_green",
        normal = "light_green",
        normal_prefix = "dark_gray",
        list_header = "dark_gray",
    },
    nick_colors = {
        "light_red", "light_green", "light_yellow", "light_blue",
        "light_magenta", "cyan", "light_cyan", "white",
    },
    formats = {
        status_format = "%T %N%# %@%C%+ %W %A %H%B %F %Q%M",
        input_prompt = "> ",
        join = "* $0 has joined $1",
        part = "* $0 has left $1 ($2)",
        quit = "* $0 has quit IRC ($1)",
        kick = "* $0 was kicked from $1 by $2 ($3)",
        nick = "* $0 is now known as $1",
        mode = "* $0 sets mode: $1",
        topic = "* $0 set topic to: $1",
        msg = "<$0> $1",
        notice = "-$0- $1",
        action = "* $0 $1",
        public = "<$0> $1",
    },
})
